version: '3'
services:
  database:
    image: mongo:5.0.9
    environment:
      - MONGO_INITDB_DATABASE=database-name
    ports:
      - 27017:27017
  app:
    volumes:
      - ${PWD}:${PWD}
    working_dir: ${PWD}
    image: golang:1.18
    environment:
      - MONGO_URI=mongodb://database:27017
      - MONGO_DB_NAME=database-name
    command: go run .
    ports:
    - 8080:1323