version: '3'
services:
  mongo:
    container_name: database
    image: mongo:5.0.9
    environment:
      - MONGO_INITDB_DATABASE=database-name
    ports:
      - 27017:27017
  app:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=database-name
    command: go run .
    ports:
    - 8080:1323
    volumes:
      - ${PWD}:${PWD}
    working_dir: ${PWD}