version: '3'
services:
  mongo:
    container_name: database
    image: mongo:5.0.9
    environment:
      - MONGO_INITDB_DATABASE=database-name
    ports:
      - 27017:27017
  app:
    container_name: application
    volumes:
      - ${PWD}:${PWD}
      - go:/go
      - rootgocache:/root/.cache
    working_dir: ${PWD}
    image: golang:1.18
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=database-name
    command: go run .
    ports:
    - 8080:1323
volumes:
  go:
  rootgocache: