version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
    - ${PWD}:${PWD}
    - /var/run/docker.sock:/var/run/docker.sock
    - ~/.gitconfig:/home/utrade/.gitconfig
